server:
  port: ${PORT:8761}
  
message: Spring Cloud Config EurekaServer

spring:
  application:
    name: eurekaServer

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
